version: "3.7"
services:
  #  爬虫服务
  crawlerinit:
    image: zhlcy2022/crawlerinit
    #    build: ./crawler
    depends_on:
      - mongo
      - database
    volumes:
      - ./crawlerinit:/app
    command: sh -c "python main.py"
    environment:
      BASE_URL: http://database:8000
      SELENIUM: http://selenium-hub:4444
  crawlercurrent:
    image: zhlcy2022/crawlercurrent
    #    build: ./crawler
    depends_on:
      - mongo
      - database
    volumes:
      - ./crawlercurrent:/app
    command: sh -c "python main.py"
    environment:
      BASE_URL: http://database:8000
      SELENIUM: http://selenium-hub:4444

  #  数据库服务
  database:
    image: zhlcy2022/database
    #    build: ./database
    depends_on:
      - mongo
#    volumes:
#      - ./database:/app
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: mongodb://root:example@mongo:27017
      PORT: 8000
    #  邮件服务
  email:
    image: zhlcy2022/email
    #    build: ./email
    depends_on:
      - mongo
      - database
      - crawlerinit
      - crawlercurrent
    volumes:
      - ./email:/app
    command: sh -c "yarn install && yarn run dev"
    environment:
      BASE_URL: http://database:8000
      # email
      EMAIL_HOST: 'smtp.qq.com'
      EMAIL_PORT: 465
      # 你的QQ账号
      EMAIL_USER: 601095001@qq.com
      EMAIL_PASSWORD: bwgnohvkfyyhbdca
      # 延迟监听时间，单位: hour
      DELAY_TIME_SPAN: 0
      # 监听实时时间之前多久的数据
      MONITOR_TIME_SPAN: 3
      # 让分阈值
      INC_THRESHOLD: 10
      DES_THRESHOLD: 10
      # 接收邮箱
      RECEIVE_EMAIL: 759126132@qq.com
  chrome:
    image: zhlcy2022/chrome
    build: ./chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  chrome2:
    image: zhlcy2022/chrome
    build: ./chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  chrome3:
    image: zhlcy2022/chrome
    build: ./chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  #    environment:

  #  seleniumGrid:
  #    image: selenium/standalone-chrome
  #    shm_size: 2gb
  #    environment:
  #      - SE_NODE_SESSION_TIMEOUT = 10
  #    ports:
  #      - "4444:4444"
  #      - "7900:7900"
  # mongodb
  mongo:
    image: mongo
    command: --wiredTigerCacheSizeGB 2
    restart: always
#    volumes:
#      - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # 数据库在线编辑
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017