version: "3.7"
services:
  analysis:
    image: zhlcy2022/analysis
#    build: ./analysis
    depends_on:
      - mongo
      - database-analysis
    volumes:
      - ./analysis:/app
    command: sh -c "python main.py"
    ports:
      - "5000:5000"
    environment:
      BASE_URL: http://database-analysis:8000
    deploy:
      resources:
        limits:
          #cpus: '0.50'
          memory: 8gb
  #    oom_kill_disable: true

#  proxys:
#    image: zhlcy2022/proxys
##    build: ./proxys
#    depends_on:
#      - mongo
#      - database
#    volumes:
#      - ./proxys:/app
#    command: sh -c "python main.py"
#    environment:
#      BASE_URL: http://database:8000

  #  爬虫服务
  crawlerinit:
    image: zhlcy2022/crawlerinit
#    build: ./crawlerinit
    #    build: ./crawler
    depends_on:
      - mongo
      - database
    volumes:
      - ./crawlerinit:/app
    command: sh -c "python3 main.py"
    environment:
      BASE_URL: http://database:8000
      SELENIUM: http://selenium-hub:4444
  crawlercurrent:
    image: zhlcy2022/crawlercurrent
#    build: ./crawlercurrent
    #    build: ./crawler
    depends_on:
      - mongo
      - database
    volumes:
      - ./crawlercurrent:/app
    command: sh -c "python3 main.py"
    environment:
      BASE_URL: http://database:8000
      SELENIUM: http://selenium-hub:4444
  crawlerhistory:
    image: zhlcy2022/crawlerhistory
#    build: ./crawlerhistory
    #    build: ./crawler
    depends_on:
      - mongo
      - database
    volumes:
      - ./crawlerhistory:/app
    command: sh -c "python3 main.py"
    environment:
      BASE_URL: http://database:8000
      SELENIUM: http://selenium-hub:4444
  crawlerhistory2:
    image: zhlcy2022/crawlerhistory2
    #    build: ./crawlerhistory
    #    build: ./crawler
    depends_on:
      - mongo
      - database
    volumes:
      - ./crawlerhistory2:/app
    command: sh -c "python3 main.py"
    environment:
      BASE_URL: http://database:8000
      SELENIUM: http://selenium-hub:4444
  crawlerrecords:
    image: zhlcy2022/crawlerrecords
#    build: ./crawlerrecords
    depends_on:
      - mongo
      - database
    volumes:
      - ./crawlerrecords:/app
    command: sh -c "python3 main.py"
    environment:
      BASE_URL: http://database:8000
      SELENIUM: http://selenium-hub:4444
    ports:
      - "6000:6000"
  emailvalid:
    image: zhlcy2022/emailvalid
#    build: ./emailvalid
    depends_on:
      - mongo
      - database
    volumes:
      - ./emailvalid:/app
    command: sh -c "python3 export_r.py"
    environment:
      BASE_URL: http://database:8000







  #  数据库服务
  database:
    image: zhlcy2022/database
#    build: ./database
    #    build: ./database
    depends_on:
      - mongo
    volumes:
      - ./database:/app
    command: sh -c "yarn install && yarn start"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: mongodb://root:example@mongo:27017
      ANALYSIS_URL: http://analysis:5000
      PORT: 8000
  database-analysis:
    image: zhlcy2022/database
#    build: ./database
    depends_on:
      - mongo
    volumes:
      - ./database:/app
    command: sh -c "yarn install && yarn start"
    environment:
      DATABASE_URI: mongodb://root:example@mongo:27017
      ANALYSIS_URL: http://analysis:5000
      PORT: 8000


  #  邮件服务
  emailcreator:
    image: zhlcy2022/emailcreator
#    build: ./emailcreator
    #    build: ./email
    depends_on:
      - mongo
      - database
      - crawlerinit
      - crawlercurrent
    volumes:
      - ./emailcreator:/app
    command: sh -c "yarn install && yarn start"
    environment:
      BASE_URL: http://database:8000
      CRAWLER_RECORDS: http://crawlerrecords:6000
  emailsender:
    image: zhlcy2022/emailsender
#    build: ./emailsender
    #    build: ./email
    depends_on:
      - mongo
      - database
      - crawlerinit
      - crawlercurrent
    volumes:
      - ./emailsender:/app
    command: sh -c "yarn install && yarn start"
    environment:
      BASE_URL: http://database:8000
      CRAWLER_RECORDS: http://crawlerrecords:6000


  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
#    image: zhlcy2022/chrome
    build: ./chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  chrome2:
#    image: zhlcy2022/chrome
    build: ./chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  chrome3:
#    image: zhlcy2022/chrome
    build: ./chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443





  # mongodb
  mongo:
    image: mongo
    command: --wiredTigerCacheSizeGB 2
    restart: always
    #    volumes:
    #      - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # 数据库在线编辑
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017