version: "3.7"
services:
#  #  爬虫服务
#  crawler:
#    image: crawler
#    build: ./crawler
#    depends_on:
#      - database
#    volumes:
#      - ./crawler:/app
#    command: sh -c "yarn dev"
#    ports:
#      - "3000:3000"
  #  数据库服务
  database:
    image: database
    build: ./database
    depends_on:
      - mongo
    volumes:
      - ./database:/app
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: mongodb://root:example@mongo:27017/
      PORT: 8000
    #  邮件服务
  email:
    image: email
    build: ./email
    depends_on:
      - mongo
    volumes:
      - ./email:/app
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: mongodb://root:example@mongo:27017/
      PORT: 8000
      # email
      EMAIL_HOST: 'smtp.qq.com'
      EMAIL_PORT: 465
      # 你的QQ账号
      EMAIL_USER: 759126132@qq.com
      EMAIL_PASSWORD: evrbcmehxjelbcgd
      # 延迟监听时间，单位: hour
      DELAY_TIME_SPAN: 0
      # 监听实时时间之前多久的数据
      MONITOR_TIME_SPAN: 1
      # 让分阈值
      THRESHOLD: 0.5
      # 接收邮箱
      RECEIVE_EMAIL: 601095001@qq.com
  # mongodb
  mongo:
    image: mongo
    command: --wiredTigerCacheSizeGB 2
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  # 数据库在线编辑
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
